;;; codex-ide-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from codex-ide.el

(let ((loads (get 'codex-ide 'custom-loads))) (if (member '"codex-ide" loads) nil (put 'codex-ide 'custom-loads (cons '"codex-ide" loads)) (put 'tools 'custom-loads (cons 'codex-ide (get 'tools 'custom-loads)))))
(defvar codex-ide-cli-path "codex"
  "Path to the Codex CLI executable.")
(custom-autoload 'codex-ide-cli-path "codex-ide" t)
(defvar codex-ide-buffer-name-function #'codex-ide--default-buffer-name
  "Function used to derive the Codex session buffer name.")
(custom-autoload 'codex-ide-buffer-name-function "codex-ide" t)
(defvar codex-ide-cli-extra-flags ""
  "Additional flags appended to the `codex app-server` command.")
(custom-autoload 'codex-ide-cli-extra-flags "codex-ide" t)
(defvar codex-ide-model nil
  "Optional model name for new or resumed threads and later turns.")
(custom-autoload 'codex-ide-model "codex-ide" t)
(defvar codex-ide-reasoning-effort nil
  "Optional reasoning effort for new Codex turns.")
(custom-autoload 'codex-ide-reasoning-effort "codex-ide" t)
(defvar codex-ide-running-submit-action 'steer
  "Action used by `codex-ide-submit' while a Codex turn is running.")
(custom-autoload 'codex-ide-running-submit-action "codex-ide" t)
(defvar codex-ide-prompt-placeholder-text "Tell Codex what to do..."
  "Placeholder text displayed in an empty idle Codex prompt.")
(custom-autoload 'codex-ide-prompt-placeholder-text "codex-ide" t)
(defvar codex-ide-steering-placeholder-text "Running..."
  "Placeholder text displayed in an empty Codex prompt during a running turn.")
(custom-autoload 'codex-ide-steering-placeholder-text "codex-ide" t)
(defvar codex-ide-placeholder-ellipsis-animation-interval 0.5
  "Seconds between animated trailing ellipsis frames in busy prompt help.
When nil or zero, busy prompt help displays its text unchanged.")
(custom-autoload 'codex-ide-placeholder-ellipsis-animation-interval "codex-ide" t)
(defvar codex-ide-status-placeholder-text-alist '(("approval" . "Seeking approval...") ("interrupting" . "Interrupting..."))
  "Alist mapping Codex session statuses to active prompt placeholder text.

Entries are matched against lowercase status strings.  When a busy session
status has no entry here, `codex-ide-steering-placeholder-text' is used.")
(custom-autoload 'codex-ide-status-placeholder-text-alist "codex-ide" t)
(defvar codex-ide-session-baseline-prompt "\n- You are a Codex server running inside Emacs.\n- You can use MCP tools to inspect and interact with the running Emacs session.\n- Interpret Emacs terminology as relevant context to the user's request: buffers, regions, windows, point, mark, current file, etc.\n- Responses are rendered as Markdown in an Emacs buffer.\n- Markdown pipe tables are rendered as visible tables.\n- In table cells, wrap code-like identifiers, filenames, paths, symbols, and expressions in backticks.\n- Use markdown links for code references, for example [`foo.el`](/tmp/foo.el#L3C2).\n- Avoid bare underscores or asterisks for code-like text inside tables; use backticks instead.\n- Do not needlessly use Emacs commands to accomplish agent tasks."
  "Optional baseline prompt injected into the first real prompt of a new thread.")
(custom-autoload 'codex-ide-session-baseline-prompt "codex-ide" t)
(defvar codex-ide-buffer-name-prefix "codex"
  "Prefix used when creating Codex session buffer names.")
(custom-autoload 'codex-ide-buffer-name-prefix "codex-ide" t)
(defvar codex-ide-new-session-split nil
  "Window split direction to use when showing newly created Codex sessions.")
(custom-autoload 'codex-ide-new-session-split "codex-ide" t)
(defvar codex-ide-diff-inline-fold-threshold 12
  "Maximum inline diff lines to show before folding by default.
When nil, inline diffs never start folded.")
(custom-autoload 'codex-ide-diff-inline-fold-threshold "codex-ide" t)
(defvar codex-ide-diff-auto-display-policy 'never
  "When Codex should auto-display file-change diffs in a standalone diff buffer.")
(custom-autoload 'codex-ide-diff-auto-display-policy "codex-ide" t)
(defvar codex-ide-session-enable-visual-line-mode t
  "Whether Codex session buffers should enable `visual-line-mode' by default.")
(custom-autoload 'codex-ide-session-enable-visual-line-mode "codex-ide" t)
(defvar codex-ide-approval-policy "on-request"
  "Approval policy for new or resumed Codex threads and later turns.")
(custom-autoload 'codex-ide-approval-policy "codex-ide" t)
(defvar codex-ide-sandbox-mode "workspace-write"
  "Sandbox mode for new or resumed Codex threads and later turns.")
(custom-autoload 'codex-ide-sandbox-mode "codex-ide" t)
(defvar codex-ide-personality "pragmatic"
  "Personality for new or resumed Codex threads and later turns.")
(custom-autoload 'codex-ide-personality "codex-ide" t)
(defvar codex-ide-request-timeout 10
  "Seconds to wait for synchronous app-server responses.")
(custom-autoload 'codex-ide-request-timeout "codex-ide" t)
(defvar codex-ide-log-max-lines 10000
  "Maximum number of lines to keep in each Codex log buffer.")
(custom-autoload 'codex-ide-log-max-lines "codex-ide" t)
(defvar codex-ide-logging-enabled nil
  "Whether codex-ide should create and write diagnostic log buffers.")
(custom-autoload 'codex-ide-logging-enabled "codex-ide" t)
(defvar codex-ide-log-stream-deltas nil
  "Whether to log every streamed output delta.")
(custom-autoload 'codex-ide-log-stream-deltas "codex-ide" t)
(defvar codex-ide-resume-summary-turn-limit 100
  "How many recent turns to summarize when resuming a stored thread.")
(custom-autoload 'codex-ide-resume-summary-turn-limit "codex-ide" t)
(defvar codex-ide-thread-list-default-limit 100
  "Default number of stored threads to request when listing threads.

This value is used when protocol callers do not pass an explicit
thread-list limit.")
(custom-autoload 'codex-ide-thread-list-default-limit "codex-ide" t)
(autoload 'codex-ide-toggle-logging-enabled "codex-ide"
  "Toggle `codex-ide-logging-enabled' interactively." t)
(register-definition-prefixes "codex-ide" '("codex-ide-buffer-display-when-approval-required"))


;;; Generated autoloads from codex-ide-mcp-bridge.el

(defvar codex-ide-enable-emacs-tool-bridge nil
  "Whether codex-ide should expose Emacs tools to Codex via MCP.

When non-nil, codex-ide starts an MCP bridge server alongside `codex app-server'
and ensures the current Emacs instance is reachable via `emacsclient'.")
(custom-autoload 'codex-ide-enable-emacs-tool-bridge "codex-ide-mcp-bridge" t)
(defvar codex-ide-want-mcp-bridge 'prompt
  "Whether codex-ide should start the Emacs MCP bridge.

When nil, do not start the bridge.  When t, start the bridge without prompting.
When `prompt', ask before enabling the bridge, matching the historical startup
behavior.")
(custom-autoload 'codex-ide-want-mcp-bridge "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-tool-bridge-name "codex-ide-emacs-mcp"
  "Name used when registering the Emacs MCP bridge with Codex.")
(custom-autoload 'codex-ide-emacs-tool-bridge-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-python-command "python3"
  "Python executable used to launch the standalone Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-python-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-emacsclient-command "emacsclient"
  "Path to the `emacsclient' executable used by the bridge.")
(custom-autoload 'codex-ide-emacs-bridge-emacsclient-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-script-path nil
  "Path to the standalone Emacs MCP bridge script.

When nil, codex-ide uses `bin/codex-ide-mcp-server.py' from the package directory.")
(custom-autoload 'codex-ide-emacs-bridge-script-path "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-server-name nil
  "Server name the bridge should use with `emacsclient'.

When nil, use the current value of `server-name'.")
(custom-autoload 'codex-ide-emacs-bridge-server-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-suppress-server-start-prompts nil
  "When non-nil, start the Emacs server for the bridge without prompting.

This only affects explicit calls to `codex-ide-mcp-bridge-ensure-server'.  Session
startup now prompts once about enabling the Emacs tool bridge, and enabling the
bridge starts the Emacs server automatically when needed.")
(custom-autoload 'codex-ide-suppress-server-start-prompts "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-startup-timeout 10
  "Startup timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-startup-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-tool-timeout 60
  "Tool-call timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-tool-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-require-approval nil
  "Whether Emacs MCP bridge tool calls should require user approval.

When nil, `codex-ide' auto-accepts approval-like MCP elicitations that clearly
refer to the configured Emacs MCP bridge server or one of its tools.")
(custom-autoload 'codex-ide-emacs-bridge-require-approval "codex-ide-mcp-bridge" t)
(autoload 'codex-ide-mcp-bridge-request-exempt-from-approval-p "codex-ide-mcp-bridge"
  "Return non-nil when PARAMS describe an Emacs MCP bridge request.

This is used to bypass bridge-originated elicitation prompts when
`codex-ide-emacs-bridge-require-approval' is nil.

(fn PARAMS)")
(autoload 'codex-ide-mcp-bridge-enabled-p "codex-ide-mcp-bridge"
  "Return non-nil when the Emacs MCP bridge should be enabled.")
(autoload 'codex-ide-mcp-bridge-enable "codex-ide-mcp-bridge"
  "Enable the Emacs MCP bridge and ensure the target Emacs server is running.")
(autoload 'codex-ide-mcp-bridge-disable "codex-ide-mcp-bridge"
  "Disable the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge-prompt-to-enable "codex-ide-mcp-bridge"
  "Prompt once to enable the Emacs MCP bridge for session startup.")
(autoload 'codex-ide-mcp-bridge-status "codex-ide-mcp-bridge"
  "Return an alist describing the current Emacs bridge configuration.")
(autoload 'codex-ide-mcp-bridge-ensure-server "codex-ide-mcp-bridge"
  "Ensure the target Emacs server for the bridge is running.")
(autoload 'codex-ide-mcp-bridge-mcp-config-args "codex-ide-mcp-bridge"
  "Return `codex app-server' CLI args that register the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge--json-tool-call "codex-ide-mcp-bridge"
  "Decode JSON PAYLOAD, dispatch a bridge tool call, and return JSON.

(fn PAYLOAD)")
(register-definition-prefixes "codex-ide-mcp-bridge" '("codex-ide-mcp-bridge--"))


;;; Generated autoloads from codex-ide-transient.el

(autoload 'codex-ide-menu "codex-ide-transient" nil t)
(autoload 'codex-ide-config-menu "codex-ide-transient" nil t)
(autoload 'codex-ide-debug-menu "codex-ide-transient" nil t)
(register-definition-prefixes "codex-ide-transient" '("codex-ide--"))


;;; Generated autoloads from codex-ide-mcp-elicitation.el

(register-definition-prefixes "codex-ide-mcp-elicitation" '("codex-ide-mcp-elicitation-"))


;;; Generated autoloads from codex-ide-mcp-bridge.el

(defvar codex-ide-enable-emacs-tool-bridge nil "\
Whether codex-ide should expose Emacs tools to Codex via MCP.

When non-nil, codex-ide starts an MCP bridge server alongside `codex app-server'
and ensures the current Emacs instance is reachable via `emacsclient'.")
(custom-autoload 'codex-ide-enable-emacs-tool-bridge "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-tool-bridge-name "emacs" "\
Name used when registering the Emacs MCP bridge with Codex.")
(custom-autoload 'codex-ide-emacs-tool-bridge-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-python-command "python3" "\
Python executable used to launch the standalone Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-python-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-emacsclient-command "emacsclient" "\
Path to the `emacsclient' executable used by the bridge.")
(custom-autoload 'codex-ide-emacs-bridge-emacsclient-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-script-path nil "\
Path to the standalone Emacs MCP bridge script.

When nil, codex-ide uses `bin/codex-ide-mcp-server.py' from the package directory.")
(custom-autoload 'codex-ide-emacs-bridge-script-path "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-server-name nil "\
Server name the bridge should use with `emacsclient'.

When nil, use the current value of `server-name'.")
(custom-autoload 'codex-ide-emacs-bridge-server-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-suppress-server-start-prompts nil "\
When non-nil, start the Emacs server for the bridge without prompting.

This only affects explicit calls to `codex-ide-mcp-bridge-ensure-server'.  Session
startup now prompts once about enabling the Emacs tool bridge, and enabling the
bridge starts the Emacs server automatically when needed.")
(custom-autoload 'codex-ide-suppress-server-start-prompts "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-startup-timeout 10 "\
Startup timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-startup-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-tool-timeout 60 "\
Tool-call timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-tool-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-require-approval nil "\
Whether Emacs MCP bridge tool calls should require user approval.

When nil, `codex-ide' auto-accepts approval requests and approval-like MCP
elicitations that clearly refer to the configured Emacs MCP bridge server or
one of its tools.")
(custom-autoload 'codex-ide-emacs-bridge-require-approval "codex-ide-mcp-bridge" t)
(autoload 'codex-ide-mcp-bridge-request-exempt-from-approval-p "codex-ide-mcp-bridge" "\
Return non-nil when PARAMS describe an Emacs MCP bridge request.

This is used to bypass user confirmation for bridge-originated approval
requests when `codex-ide-emacs-bridge-require-approval' is nil.

(fn PARAMS)")
(autoload 'codex-ide-mcp-bridge-enabled-p "codex-ide-mcp-bridge" "\
Return non-nil when the Emacs MCP bridge should be enabled.")
(autoload 'codex-ide-mcp-bridge-enable "codex-ide-mcp-bridge" "\
Enable the Emacs MCP bridge and ensure the target Emacs server is running.")
(autoload 'codex-ide-mcp-bridge-disable "codex-ide-mcp-bridge" "\
Disable the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge-prompt-to-enable "codex-ide-mcp-bridge" "\
Prompt once to enable the Emacs MCP bridge for session startup.")
(autoload 'codex-ide-mcp-bridge-status "codex-ide-mcp-bridge" "\
Return an alist describing the current Emacs bridge configuration.")
(autoload 'codex-ide-mcp-bridge-ensure-server "codex-ide-mcp-bridge" "\
Ensure the target Emacs server for the bridge is running.")
(autoload 'codex-ide-mcp-bridge-mcp-config-args "codex-ide-mcp-bridge" "\
Return `codex app-server' CLI args that register the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge--json-tool-call "codex-ide-mcp-bridge" "\
Decode JSON PAYLOAD, dispatch a bridge tool call, and return JSON.

(fn PAYLOAD)")
(register-definition-prefixes "codex-ide-mcp-bridge" '("codex-ide-mcp-bridge--"))


;;; Generated autoloads from codex-ide-session-buffer-list.el

(autoload 'codex-ide-session-buffer-list "codex-ide-session-buffer-list"
  "Show a tabulated list of live Codex session buffers." t)
(register-definition-prefixes "codex-ide-session-buffer-list" '("codex-ide-session-buffer-list-"))


;;; Generated autoloads from codex-ide-session-list.el

(register-definition-prefixes "codex-ide-session-list" '("codex-ide-session-list-"))


;;; Generated autoloads from codex-ide-delete-session-thread.el

(autoload 'codex-ide-delete-session-thread "codex-ide-delete-session-thread"
  "Delete Codex THREAD-ID from the active `CODEX_HOME`.

This command relies on current Codex internal storage details under
`CODEX_HOME`, specifically the persisted rollout files under the sessions
directory.  That makes it more fragile than the rest of codex-ide, which
primarily uses the public app-server API.  If Codex adds an officially
supported thread deletion API, this implementation should be replaced to use
that instead.

If a live session buffer is attached to THREAD-ID, prompt before tearing down
that session and then remove the persisted thread data from disk.

When SKIP-CONFIRMATION is non-nil, delete without prompting.  This is intended
for batch callers that already presented a single confirmation.

(fn THREAD-ID &optional SKIP-CONFIRMATION)" t)
(register-definition-prefixes "codex-ide-delete-session-thread" '("codex-ide--"))


;;; Generated autoloads from codex-ide-core.el

(register-definition-prefixes "codex-ide-core" '("codex-ide-" "make-codex-ide-session"))


;;; Generated autoloads from codex-ide-renderer.el

(register-definition-prefixes "codex-ide-renderer" '("codex-ide-"))


;;; Generated autoloads from codex-ide-debug-info.el

(autoload 'codex-ide-show-debug-info "codex-ide-debug-info"
  "Show a minibuffer summary of live Codex IDE session state." t)
(register-definition-prefixes "codex-ide-debug-info" '("codex-ide-debug-info--"))


;;; Generated autoloads from codex-ide-section.el

(register-definition-prefixes "codex-ide-section" '("codex-ide-section-"))


;;; Generated autoloads from codex-ide-status-mode.el

(defvar codex-ide-status-mode-transcript-preview-max-lines 40
  "Maximum number of transcript lines shown in expanded buffer sections.")
(custom-autoload 'codex-ide-status-mode-transcript-preview-max-lines "codex-ide-status-mode" t)
(defvar codex-ide-status-mode-auto-refresh-delay 0.1
  "Idle delay in seconds before status buffers auto-refresh after session events.")
(custom-autoload 'codex-ide-status-mode-auto-refresh-delay "codex-ide-status-mode" t)
(defvar codex-ide-status-mode-stripe-mix 0.12
  "How strongly status header striping blends toward the default foreground.

This controls the subtle alternating background used for every other session
header in `codex-ide-status-mode'.  The stripe color is computed by blending
the default background toward the default foreground by this fraction.

Smaller values produce a subtler stripe with lower contrast.  Larger values
produce a more visible stripe.  A value of 0 disables the effect entirely,
while 1 would fully replace the background with the foreground color.")
(custom-autoload 'codex-ide-status-mode-stripe-mix "codex-ide-status-mode" t)
(autoload 'codex-ide-status-mode-nav-forward "codex-ide-status-mode"
  "Move point to the next focal point in a Codex status buffer." t)
(autoload 'codex-ide-status-mode-nav-backward "codex-ide-status-mode"
  "Move point to the previous focal point in a Codex status buffer." t)
(autoload 'codex-ide-status-mode-refresh "codex-ide-status-mode"
  "Refresh the current Codex status buffer.

(fn &optional IGNORE-AUTO NOCONFIRM)" t)
(autoload 'codex-ide-status "codex-ide-status-mode"
  "Show the Codex status buffer for the current project." t)
(register-definition-prefixes "codex-ide-status-mode" '("codex-ide-status-mode"))


;;; Generated autoloads from codex-ide-nav.el

(autoload 'codex-ide-nav-button-forward "codex-ide-nav"
  "Move to the next focal point from a Codex-owned button." t)
(autoload 'codex-ide-nav-button-backward "codex-ide-nav"
  "Move to the previous focal point from a Codex-owned button." t)
(autoload 'codex-ide-nav-forward "codex-ide-nav"
  "Move point to the next focal point in the current buffer." t)
(autoload 'codex-ide-nav-backward "codex-ide-nav"
  "Move point to the previous focal point in the current buffer." t)
(register-definition-prefixes "codex-ide-nav" '("codex-ide-nav-"))


;;; Generated autoloads from codex-ide-utils.el

(register-definition-prefixes "codex-ide-utils" '("codex-ide-"))


;;; Generated autoloads from codex-ide-transcript.el

(autoload 'codex-ide-prompt "codex-ide-transcript"
  "Prompt for a Codex message in the minibuffer and submit it from the Codex buffer." t)
(autoload 'codex-ide-previous-prompt-history "codex-ide-transcript"
  "Replace the current prompt with the previous prompt from history." t)
(autoload 'codex-ide-next-prompt-history "codex-ide-transcript"
  "Replace the current prompt with the next prompt from history." t)
(autoload 'codex-ide-previous-prompt-line "codex-ide-transcript"
  "Jump to the previous user prompt line in the session buffer." t)
(autoload 'codex-ide-next-prompt-line "codex-ide-transcript"
  "Jump to the next user prompt line in the session buffer." t)
(autoload 'codex-ide-submit "codex-ide-transcript"
  "Submit the current in-buffer prompt to Codex." t)
(autoload 'codex-ide-steer "codex-ide-transcript"
  "Submit the current prompt as steering input to the active Codex turn." t)
(autoload 'codex-ide-queue "codex-ide-transcript"
  "Queue the current prompt as the next Codex turn." t)
(register-definition-prefixes "codex-ide-transcript" '("codex-ide-"))


;;; Generated autoloads from codex-ide-context.el

(register-definition-prefixes "codex-ide-context" '("codex-ide--"))


;;; Generated autoloads from codex-ide-errors.el

(register-definition-prefixes "codex-ide-errors" '("codex-ide--"))


;;; Generated autoloads from codex-ide-log.el

(register-definition-prefixes "codex-ide-log" '("codex-ide-"))


;;; Generated autoloads from codex-ide-protocol.el

(register-definition-prefixes "codex-ide-protocol" '("codex-ide--"))


;;; Generated autoloads from codex-ide-session.el

(autoload 'codex-ide "codex-ide-session"
  "Start Codex for the current project or directory." t)
(autoload 'codex-ide-continue "codex-ide-session"
  "Resume the most recent Codex session for the current directory." t)
(autoload 'codex-ide-show-cli-info "codex-ide-session"
  "Report Codex CLI availability and version." t)
(autoload 'codex-ide-stop "codex-ide-session"
  "Stop the Codex session associated with the current session buffer." t)
(autoload 'codex-ide-reset-current-session "codex-ide-session"
  "Stop the current Codex session and start a new one in the same buffer." t)
(autoload 'codex-ide-switch-to-buffer "codex-ide-session"
  "Show the Codex buffer for the current project." t)
(autoload 'codex-ide-interrupt "codex-ide-session"
  "Interrupt the active Codex turn for the current project." t)
(register-definition-prefixes "codex-ide-session" '("codex-ide--"))


;;; Generated autoloads from codex-ide-session-mode.el

(autoload 'codex-ide-session-mode-nav-forward "codex-ide-session-mode"
"Move point to the next focal point in a Codex session buffer." t)
(autoload 'codex-ide-session-mode-nav-backward "codex-ide-session-mode"
"Move point to the previous focal point in a Codex session buffer." t)
(autoload 'codex-ide-session-mode "codex-ide-session-mode"
"Major mode for Codex app-server session buffers.

* \\<codex-ide-session-mode-map>\\[codex-ide-submit] submits the active prompt.

* \\[codex-ide-interrupt] interrupts the current turn.

* \\[codex-ide-session-diff-open] opens the session diff buffer.

* \\[codex-ide-previous-prompt-line] and \\[codex-ide-next-prompt-line] move between prompt lines.

* \\[codex-ide-session-mode-nav-forward] and \\[codex-ide-session-mode-nav-backward] move between transcript focal points, including
  buttons, submitted prompts, and the active prompt.

When point is in the active prompt, `codex-ide-session-prompt-minor-mode'
adds these bindings:

* \\<codex-ide-session-prompt-minor-mode-map>\\[codex-ide-previous-prompt-history] and \\[codex-ide-next-prompt-history] move through prompt history.

In addition to any hooks its parent mode `text-mode' might have run,
this mode runs the hook `codex-ide-session-mode-hook', as the final or
penultimate step during initialization." t)
(register-definition-prefixes "codex-ide-session-mode" '("codex-ide-"))


;;; Generated autoloads from codex-ide-threads.el

(register-definition-prefixes "codex-ide-threads" '("codex-ide--"))


;;; Generated autoloads from codex-ide-window.el

(register-definition-prefixes "codex-ide-window" '("codex-ide-"))


;;; Generated autoloads from codex-ide-config.el

(register-definition-prefixes "codex-ide-config" '("codex-ide-config-"))


;;; Generated autoloads from codex-ide-diff-data.el

(register-definition-prefixes "codex-ide-diff-data" '("codex-ide-"))


;;; Generated autoloads from codex-ide-diff-view.el

(autoload 'codex-ide-session-diff-open "codex-ide-diff-view"
"Open or reuse the canonical session diff buffer for SESSION.

(fn &optional SESSION)" t)
(autoload 'codex-ide-diff-open-combined-turn-buffer "codex-ide-diff-view"
"Open the combined diff for SESSION TURN-ID in a standalone diff buffer.
When called interactively with nil TURN-ID, use the last transcript turn at or
above point.  Otherwise, when TURN-ID is nil, prefer the running turn and
otherwise use the most recent completed turn.

(fn &optional SESSION TURN-ID)" t)
(register-definition-prefixes "codex-ide-diff-view" '("codex-ide-"))


;;; Generated autoloads from codex-ide-rollout.el

(register-definition-prefixes "codex-ide-rollout" '("codex-ide-rollout-"))



;;; Generated autoloads from codex-ide-thread-history.el

(register-definition-prefixes "codex-ide-thread-history" '("codex-ide--"))

;;; End of scraped data

(provide 'codex-ide-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; codex-ide-autoloads.el ends here
